version: '3.8'

services:
  pranav-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pranav-agent
    volumes:
      # Mount the config directory to allow configuration changes without rebuilding
      - ./config:/app/config
      # Mount logs directory for persistence
      - ./logs:/app/logs
    environment:
      - ENVIRONMENT=production
      # Add any other environment variables your agent might need
    restart: unless-stopped
    # If you implement an API server, uncomment the ports section
    # ports:
    #   - "5000:5000"